### PR TITLE
feat():added number of clients connected in a chat

### PR DESCRIPTION
**Pull request by bhargav794**
hello, I've added a feature to see the number of clients connected in the chat anyone who is connected to the server can see how many people are active in the group. If any style changes are needed please reply and I'm more than happy to do them. Here I've attached a video for reference.

https://user-images.githubusercontent.com/66371186/131826369-b19ffb9b-20fe-4c87-af26-55aa0944d7dd.mp4

### CODE REVIEW

**Comment by guptasajal411** [comment]
Thanks for your contribution! The commits look good to me, I'll merge them. The client side JS is very large tbh 🤔 I will minify that

**Comment by guptasajal411** [comment]
Your changes are live now! You can check out the live deployment **[here](https://try-chatbud.herokuapp.com/)**. Again, thanks for contributing to Chatbud and contributing to Open Source Software 😀

**Comment by bhargav794** [comment]
>Your changes are live now!

Thank you for merging changes.
Also I'm wondering if there is any specific reason of why there are Es5 style functions instead of arrow functions

**Comment by guptasajal411** [comment]
There is no specific reason, personally I like ES5 functions more than arrow functions (unpopular opinion :P)

**Comment by bhargav794** [comment]
Maybe we can try to add emoji support to ChatBud next

**Comment by guptasajal411** [comment]
That's a good idea. I think you should open an issue for this and I will start working 👍. You also get green squares 🟩 for raising issues in a repo

**Pull request merged**
